"""Offline embedding builder for Contact Lens.

Reads the exact strings Dart will embed (tool/embed/texts.json, produced by
dump_texts.dart) and writes a generated Dart file holding their real semantic
vectors:

    lib/rag/semantic/precomputed_embeddings.g.dart

The embeddings come from a multilingual MiniLM model run through ONNX Runtime
(via fastembed -- no torch). Because the eval/demo query set is fixed, the
vectors are precomputed once at build time and baked in as a const map, so the
Flutter Web demo and `dart run` both get true semantics with zero runtime
inference and no model download. Arbitrary typed queries that are not in the map
fall back to a zero vector (semantic contributes nothing -> lexical behavior).

Usage (from repo root, with tool/embed/.venv active):

    dart run tool/embed/dump_texts.dart > tool/embed/texts.json
    python tool/embed/build_embeddings.py
"""

from __future__ import annotations

import json
import math
import os
import sys

# Symmetric multilingual model preferred (no query/passage prefix needed);
# e5 fallback needs asymmetric prefixes. (model_name, scheme)
CANDIDATE_MODELS = [
    ("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2", "plain"),
    ("intfloat/multilingual-e5-small", "e5"),
    ("intfloat/multilingual-e5-large", "e5"),
]

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
TEXTS = os.path.join(HERE, "texts.json")
OUT = os.path.join(REPO, "lib", "rag", "semantic", "precomputed_embeddings.g.dart")


def pick_model(TextEmbedding):
    supported = {m["model"] for m in TextEmbedding.list_supported_models()}
    for name, scheme in CANDIDATE_MODELS:
        if name in supported:
            return name, scheme
    raise SystemExit(
        "No preferred multilingual model is supported by this fastembed build.\n"
        "Supported models:\n  " + "\n  ".join(sorted(supported))
    )


def prefixed(text: str, kind: str, scheme: str) -> str:
    if scheme == "e5":
        return ("query: " if kind == "query" else "passage: ") + text
    return text


def l2_normalize(vec):
    norm = math.sqrt(sum(v * v for v in vec))
    if norm == 0:
        return [0.0 for _ in vec]
    return [v / norm for v in vec]


def dart_string(s: str) -> str:
    out = s.replace("\\", "\\\\").replace("$", "\\$").replace('"', '\\"')
    out = out.replace("\n", "\\n").replace("\r", "")
    return f'"{out}"'


def dart_vector(vec) -> str:
    # Compact, deterministic doubles; 6 sig figs keeps the file small while
    # preserving cosine ordering.
    return "[" + ", ".join(f"{v:.6f}" for v in vec) + "]"


def main() -> None:
    try:
        from fastembed import TextEmbedding
    except ImportError:
        raise SystemExit(
            "fastembed is not installed. Activate tool/embed/.venv and run "
            "`pip install fastembed numpy`."
        )

    with open(TEXTS, encoding="utf-8") as fh:
        rows = json.load(fh)

    model_name, scheme = pick_model(TextEmbedding)
    print(f"[build_embeddings] model={model_name} scheme={scheme} texts={len(rows)}", file=sys.stderr)

    model = TextEmbedding(model_name=model_name)
    inputs = [prefixed(r["text"], r["kind"], scheme) for r in rows]
    vectors = [l2_normalize([float(x) for x in v]) for v in model.embed(inputs)]

    dim = len(vectors[0]) if vectors else 0
    if any(len(v) != dim for v in vectors):
        raise SystemExit("inconsistent embedding dimensions")

    lines = [
        "// GENERATED by tool/embed/build_embeddings.py -- do not edit by hand.",
        f"// model: {model_name} (ONNX via fastembed); dim: {dim}; texts: {len(rows)}.",
        "//",
        "// Real multilingual semantic vectors for the fixed eval/demo string set,",
        "// keyed by the exact text Dart passes to EmbeddingModel.embed.",
        "",
        f"const String precomputedEmbeddingModelId = '{model_name}';",
        f"const int precomputedEmbeddingDim = {dim};",
        "",
        "const Map<String, List<double>> precomputedEmbeddings = {",
    ]
    for row, vec in zip(rows, vectors):
        lines.append(f"  {dart_string(row['text'])}: {dart_vector(vec)},")
    lines.append("};")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"[build_embeddings] wrote {OUT} ({len(rows)} vectors, dim {dim})", file=sys.stderr)


if __name__ == "__main__":
    main()
